name:  dining_philosophers
version: 0.7.0

description: Solutions for the dining philosopher problem.

authors:
- Karl Guggisberg <karl.guggisberg@guggis.ch>

dependencies:
  unittest: any
  args: any