name:  dining_philosophers
version: 0.6.0

description: Solutions for the dining philosopher problem.

authors:
- Karl Guggisberg <karl.guggisberg@guggis.ch>

dependencies:
  unittest: ">=0.11.0+2 <0.12.0"
  args: ">=0.11.0+1 <0.12.0"
